package com.alibaba.baichuan.android.trade.f;

public final class b {
    public static final String[] a = new String[]{"^http(s)?://login\\.(.*)\\.taobao.com/login\\.htm(.*)$", "^http(s)?://login\\.tmall\\.com(.*)$", "^http(s)?://login.taobao.com/member/login.jhtml(.*)$"};
    public static final String[] b = new String[]{"^http(s)?://login\\.(.*)\\.taobao\\.com/logout(.*)$"};
    public static final String[] c = new String[]{"^http(s)?://(maliprod|mclient)\\.alipay\\.com/w/(trade_pay|batch_payment)\\.do(.*)$", "^http(s)?://(mobileclientgw|maliprod)\\.stable\\.alipay\\.net/w/(trade_pay|batch_payment)\\.do(.*)$", "^http(s)?://(maliprod|mclient)\\.alipay\\.com/(trade_pay|batch_payment)\\.do(.*)$", "^http(s)?://(mobileclientgw|maliprod)\\.stable\\.alipay\\.net/(trade_pay|batch_payment)\\.do(.*)$"};
    public static final String[] d = new String[]{"^tbopen://m.taobao\\.com/tbopen/index\\.htm(.*)$"};
    public static final String[] e = new String[]{"^http(s)?://h5\\.(.*)\\.taobao\\.com/cm/snap/index\\.html(.*)", "^http(s)?://h5\\.(.*)\\.taobao\\.com/awp/base/order\\.htm(.*)", "^http(s)?://h5\\.(.*)\\.taobao\\.com/awp/base/cart\\.htm(.*)", "^http(s)?://h5\\.(.*)\\.taobao\\.com/awp/base/bag\\.htm(.*)", "^http(s)?://h5\\.(.*)\\.taobao\\.com/mlapp/cart\\.htm(.*)", "^http(s)?://h5\\.(.*)\\.taobao\\.com/cart/order\\.htm(.*)", "^http(s)?://h5\\.(.*)\\.taobao\\.com/awp/core/detail\\.htm(.*)", "^http(s)?://h5\\.(.*)\\.taobao\\.com/mlapp/olist\\.htm(.*)", "^http(s)?://shop\\.(.*)\\.taobao\\.com/shop/shopIndex\\.htm(.*)", "^http(s)?://shop\\.(.*)\\.taobao\\.com/shop/shop_index\\.htm(.*)", "^http(s)?://h5\\.(.*)\\.taobao\\.com/trade/detail\\.htm(.*)", "^http(s)?://detail\\.(.*)\\.tmall\\.(com|hk)/item\\.htm(.*)", "^http(s)?://buy\\.(.*)\\.tmall\\.(com|hk)/order/confirmOrderWap\\.htm(.*)", "^http(s)?://((?!(login|buy|s.click))\\.)(.*)\\.tmall\\.com(.*)$", "^http(s)?://buy\\.(.*)\\.tmall\\.(com|hk)/order/confirm_order_wap\\.htm(.*)", "^http(s)?://cart\\.(.*)\\.tmall\\.(com|hk)/cart/myCart\\.htm(.*)", "^http(s)?://h5\\.(.*)\\.tmall\\.(com|hk)/awp/base/order\\.htm(.*)", "^http(s)?://h5\\.(.*)\\.tmall\\.(com|hk)/cart/order\\.htm(.*)"};
    public static final String[] f = new String[]{"^http(s)?://h5\\.(.*)\\.taobao\\.com/baichuanWebViewBridge?(.*)addCart=success(.*)$"};
    public static final String[] g = new String[]{"^http(s)?://shop\\.(.*)\\.taobao.com/shop/shop_index.htm(.*)", "^http(s)?://shop\\.(.*)\\.tmall.com/shop/shop_index.htm(.*)"};
    public static final String[] h = new String[]{"^http(s)?://h5\\.(.*)\\.taobao.com/cm/snap/index\\.html(.*)", "^http(s)?://h5\\.(.*)\\.taobao\\.com/awp/core/detail\\.htm(.*)", "^http(s)?://detail\\.(.*)\\.tmall\\.(com|hk)/item\\.htm(.*)"};
    public static final String[] i = new String[]{"^http(s)?://s\\.click\\.(taobao|tmall)\\.com/(.*)"};
}
