package com.xunlei.tdlive.modal;

import android.content.Context;
import java.util.HashMap;
import java.util.HashSet;

/* compiled from: GlobalConfig */
public class b {
    public static int A = 12;
    public static int B = 450000;
    public static int C = 300000;
    public static int D = 20;
    public static int E = 5;
    public static boolean F = false;
    public static boolean G = false;
    public static String H = null;
    public static String I = null;
    public static HashSet<String> J = new HashSet();
    public static HashMap<String, String> K = new HashMap();
    public static HashMap<String, String> L = new HashMap();
    public static String M = null;
    public static String N = null;
    public static int O = 0;
    @Deprecated
    public static int P = 5;
    @Deprecated
    public static int Q = 15;
    @Deprecated
    public static int R = 25;
    public static int S = 22;
    public static int T = 18;
    public static int U = 204800;
    public static String V = null;
    public static String W = "送礼物，与主播亲密互动";
    public static String X = "新礼物上架了~";
    public static String Y = "伦家期待你的礼物哦";
    public static String Z = "今日礼包福利已发放\n还等啥，送给心动主播吧";
    public static boolean a = true;
    public static String aA = "http://h5.live.xunlei.com/video/income.html";
    public static boolean aB = true;
    public static String aC = "^http:\\/\\/biz\\.live\\.xunlei\\.com\\/caller\\?c=site&a=qrlink&roomid=(\\d*_\\d*)$";
    private static Context aD = null;
    public static String aa = "看了这么久，跟主播聊聊天吧 >";
    public static String ab = "还没给主播送礼物，赶快来试试吧 >";
    public static String ac = "喜欢是观看，爱是分享，快快分享吧 >";
    public static String ad = "当前可能不是最新版本，无法体验最新功能特性，[LINK_id=browser://url=http://live.xunlei.com/app/;line=1;color=#fe7237;text=点我更新]";
    public static String ae = "，[LINK_id=follow://host;line=1;color=#fe7237;text=← 我也关注]";
    public static String af = "[LINK_id=http://h5.live.xunlei.com/active/vehicle/index.html;line=1;color=#ff2828;text=我也要座驾]";
    public static String ag = "弹幕更炫酷，1金币／条";
    public static String ah = "点这里撩一发主播";
    public static String ai = "http://h5.live.xunlei.com/active/2017/active/weekstar/index.html";
    public static String aj = "喜欢主播？就成为真爱粉丝吧 >";
    public static String ak = "链克";
    public static String al = "看直播，礼物免费领！快来撩主播";
    public static String am = "快送礼物给主播吧";
    public static int an = 0;
    public static int ao = 30;
    public static int ap = 1440;
    public static int aq = 1440;
    public static boolean ar = true;
    public static boolean as = true;
    public static int at = 300000;
    public static int au = 0;
    public static int av = 0;
    public static int aw = 0;
    public static int ax = 0;
    public static boolean ay = false;
    public static boolean az = false;
    public static int b = 6;
    public static String[] c = new String[]{"PK专区", "当红主播PK专区"};
    public static boolean d = true;
    public static int e = 0;
    public static boolean f = false;
    public static int g = 1000;
    public static boolean h = false;
    public static boolean i = true;
    public static boolean j = false;
    public static boolean k = true;
    public static int l = -1;
    public static int m = -1;
    public static boolean n = false;
    public static String o = "应政策要求，评论需要绑定手机号";
    public static int p = 2000;
    public static int q = 0;
    public static String r = "应政策要求，评论需要绑定手机号";
    public static boolean s = false;
    public static String t = "应政策要求，连线需要绑定手机号";
    public static int u = 0;
    public static String v = "应政策要求，连线需要绑定手机号";
    public static boolean w = true;
    public static int x = 30;
    public static int y = 10000;
    public static int z = 200;
}
